# Generated by Django 3.2.9 on 2021-11-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('gen_name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'uploads',
            },
        ),
    ]
